command /heal [<player>]:
	permission: neverlandmc.heal
	permission message: &cYou cannot do this!
	trigger:
		if arg-1 isn't set:
			set the player's food level to 10
			set the player's health to 20
			message "&6You have healed yourself!"
			stop
		if arg-1 is set:
			set the arg-1's food level to 10
			set the arg-1's health to 20
			message "&6You have healed &e%arg-1%" to player
			message "&6You have been healed by &e%player%" to arg-1
			stop