command /rules:
	executable by: players
	trigger:
		message "&6Rules:"
		message "&6Rule 1: &eNo Cheating"
		message "&6Rule 2: &eNo Teaming"
		message "&6Rule 3: &eNo Racism"
		message "&6Rule 4: &eNo Spamming"
		message "&6Rule 5: &eNo begging for things."
		message "&6Rule 6: &eNo Disrespecting Players"
		message "&6Rule 7: &eNo Innapropriate Names/Skins"
		message "&6Rule 8: &eBedrock players are not allowed, due to it breaking commands."